[package]
name = "ExMarket"
version = "1.0.0"
authors = ["ExMarket Team"]

[addresses]
exmarket = "0x1af19f412568bd69930ea371a182493585cc9ad1dd7a0d77919bb8ec4f393d9c"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
